export const About = "National Service Scheme (NSS) was introduced in the year 1969 with the primary objective of developing the personality and character of the student through voluntary community service.‘Education through Service’ is the purpose of the NSS. The ideological orientation of the NSS is inspired by the ideals of Mahatma Gandhi. Very appropriately, the motto of NSS is “NOT ME, BUT YOU”. An NSS volunteer need to place the community first before self.";

export const Logo = "The logo for the NSS is based on the Giant Rath Wheel of the world-famous Konark Sun Temple (The Black Pagoda) situated in Odisha, India. The wheel portrays the cycle of creation, preservation and release. It signifies the movement in life across time and space, the symbol thus stands for continuity as well as change and implies the continuous striving of NSS for social change. The eight bars in the wheel represent 24 hours of a day. The red color indicates that the volunteer is full of young blood that is lively, active, energetic and full of high spirit. The navy-bluecolor indicates the cosmos of which the NSS is tiny part, ready to contribute its share for the welfare of the mankind.";

export const Moto = "The motto or watchword of the National Service Scheme is 'NOT ME BUT YOU’. This reflects the essence of democratic living, upholds the need for selfless service, appreciation of the other person's point of view and also to show consideration for fellow human beings. It underlines that the welfare of an individual is ultimately dependent on the welfare of society on the whole. Therefore, it should be the aim of the NSS to demonstrate this motto in its day-to-day program and the NSS volunteers shall strive for the well-being of the society."

export const History = "NSS Day is observed annually on September 24th to commemorate the launch of the National Service Scheme (NSS) in India in 1969. This day honors the tireless efforts of NSS volunteers who dedicate themselves to serving their communities and working towards the betterment of society.";

export const nss = "NSS Day is celebrated with great enthusiasm across the country. The celebrations include: Organizing rallies and awareness campaigns on social issues Conducting cleanliness drives in adopted villages and nearby areas Organizing blood donation camps and health checkups Planting trees and creating awareness about environmental protection Visiting orphanages, old age homes, and other institutions to provide aid and support The celebrations are marked by the active participation of NSS volunteers, program officers, and the local community"

export const goals = "Develop among themselves a sense of social and civic responsibility. utilise their knowledge in finding practical solutions to individual and community problems. develop competence required for group-living and sharing of responsibilities. NSS revolves around four core pillars: Youth (Yuva), Poor (Garib), Women (Mahila), and Farmers (Kisan). The scheme aims to enhance the capabilities and empowerment of individuals in these key sectors, aligning with the broader goal of all-round development. 24 September is celebrated every year as NSS Day with appropriate programmes and activities. The motto or watchword of the National Service Scheme is `NOT ME BUT YOU`."

export const Aim = "National Service Scheme (NSS) was introduced in 1969 with the primary objective of developing the personality and character of the student youth through voluntary community service. 'Education through Service' is the purpose of the NSS The broad objectives of NSS are to: (i) understand the community in which they work (ii) understand themselves in relation to their community; (iii) identify the needs and problems of the community and involve them in problem solving process; (iv) develop among themselves a sense of social and civic responsibility; "

export const DB_URL = "mongodb+srv://ByteLinguists:F1RaoqTpVV0TNLtZ@cluster0.6bmoo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"